services:
  app:
    container_name: damas_mobile
    image: damas_mobile
    build: .
    volumes: 
      - .:/app
    ports: 
      - "8081:8081"
      - "10000:10000"
    tty: true
    stdin_open: true
    devices:
      - /dev/kvm:/dev/kvm
    