#!/bin/bash

npm run lint

# Check if the lint command succeeded
if [ $? -eq 0 ]; then
    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx|json|css|md)$')

    if [ -n "${STAGED_FILES}" ]; then
        npx prettier --write $STAGED_FILES > /dev/null 2>&1
        git add $STAGED_FILES
        echo "Arquivos formatados!"
    fi
    
    echo "Commit válido! commitando..."
    exit 0
else
    echo "Código feio detectado, melhore."
    exit 1
fi