name: Build APK and Upload to GitHub Release

on:
 release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_API_URL: ${{ vars.API_URL }} 
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install 

      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/damas-paia_${{ github.event.release.tag_name }}.apk
        
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/damas-paia_${{ github.event.release.tag_name }}.apk
